<?php

	$empresas = mysql_query("SELECT * FROM company WHERE id = '1'") or die (mysql_error());
	$empresa  = mysql_fetch_assoc($empresas);

	if ($_POST['email']!=''){	
		//include ("class/class.phpmailer.php");		 
		$body  = '
			<html>
			<body><table width="500" border="0" align="center" cellpadding="2" cellspacing="2" style="font-size:11px; border:1px solid #CCC; font-family:Tahoma, Geneva, sans-serif; background-color:#FFF">
			<tr>
			<td style="font-size:16px; font-weight:bold; color:#000; background-color:#CCC">
			<img src="'.DOMINIO.'img/top_mail.jpg" width="500" height="72" border="0"  />
			</td>
			</tr>
			<tr>
			<td style="font-size:12px">Services Contact.</td>
			</tr>
			<tr>
			<td style="font-size:12px; font-weight:bold; background-color:#f4f4f4">Contact Info</td>
			</tr>
			<tr>
			<td><strong>Name and Last Name:</strong> '.cls_string($_POST['name']).'</td>
			</tr>
			<tr>
			<td><strong>Email and Phone:</strong> '.cls_string($_POST['email'].' ('.$_POST['phone'].')').'</td>
			</tr>
			<tr>
			<td><strong>Message:</strong> '.cls_string($_POST['message']).'</td>
			</tr>
			<tr>
			<td style="background-color:#f4f4f4; text-align:center">Generated by: <a href="http://maoghost.com/">maoghost.com</a></td>
			</tr>
			</table></body>
			</html>
		';
		
		$list = array($empresa[email],$_POST[email]);
		for ($i=0;$i<count($list);$i++){				 
			$owner_email = $list[$i];//$_POST[email];
			$headers  = 'MIME-Version: 1.0' . "\r\n";
			$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
			$headers .= 'To: '.cls_string($_POST['name']).' <'.$owner_email.'>' . "\r\n";
			$headers .= 'From: '.$empresa['name'].' <'.$empresa['email'].'>' . "\r\n";
			$subject = 'A message from '.$empresa['name'].' Corporate Web ' . $_POST['name'];
			$messageBody = $body;
			//if($_POST["stripHTML"] == 'true'){
				//$messageBody = strip_tags($messageBody);
			//}
			try{
				if(!mail($owner_email, $subject, $messageBody, $headers)){
					
					mensajes("Error!", "We can not send your email, please try again!");
					break;
				}else{
					$paso = true;
				}
			}catch(Exception $e){
				echo $e->getMessage() ."\n";
				break;
			}
		}//for
		
		mensajes("Process Successfully.", "Message sent Successfully");
	}//if sumito
	 
?>

<div class="row panel">
	<h3 >Contact Us</h3>
	<div class="large-7 columns  radius">
		
		
		<form data-abide action="index.php?current=contact" method="POST" >
			<div class="name-field">
				<label>Your name <small>required</small></label>
				<input type="text" name="name" required pattern="[a-zA-Z]+" placeholder="Full Name">
				<small class="error">Name is required and must be a string.</small>
			</div>
			<div class="email-field">
				<label>Email <small>required</small></label>
				<input type="email" name="email" placeholder="your@email.com" required>
				<small class="error">An email address is required.</small>
			</div>
			<div class="phone-field">
				<label>Phone <small>required</small></label>
				<input type="tel" name="phone" placeholder="1 234-567-8910" pattern="[0-9]+" required>
				<small class="error">An phone number is required.</small>
			</div>	
			<div class="message-field">
				<label>Message <small>required</small></label>
				<textarea required name="message" pattern="[a-zA-Z]+"></textarea>
				<small class="error">An Message is required.</small>
			</div>	

			<button type="submit">Submit</button>
		</form>
	</div>	
	<div class="large-5 columns  radius">
		
		<iframe width="340" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.ve/maps?q=5967+W+COLONIAL+DRIVE+ORLANDO,+FL+32808&amp;ie=UTF8&amp;hq=&amp;hnear=5967+W+Colonial+Dr,+Orlando,+Florida+32808,+United+States&amp;gl=ve&amp;t=m&amp;ll=28.552862,-81.462164&amp;spn=0.026387,0.029182&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.ve/maps?q=5967+W+COLONIAL+DRIVE+ORLANDO,+FL+32808&amp;ie=UTF8&amp;hq=&amp;hnear=5967+W+Colonial+Dr,+Orlando,+Florida+32808,+United+States&amp;gl=ve&amp;t=m&amp;ll=28.552862,-81.462164&amp;spn=0.026387,0.029182&amp;z=14&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>
	</div>
		
</div>	
                        