<?php

	$empresas = mysql_query("SELECT * FROM company WHERE id = '1'") or die (mysql_error());
	$empresa  = mysql_fetch_assoc($empresas);

	if ($_POST['email']!=''){	

		mysql_query("REPLACE INTO `mail_list` (`email`, `name`) VALUES ('".$_POST['email']."', '".$_POST['name']."');") or die (mysql_error());

		//include ("class/class.phpmailer.php");		 
		$body  = '<html>
				<body><table width="500" border="0" align="center" cellpadding="2" cellspacing="2" style="font-size:11px; border:1px solid #CCC; font-family:Tahoma, Geneva, sans-serif; background-color:#FFF">
				<tr>
				<td style="font-size:16px; font-weight:bold; color:#000; background-color:#CCC">
				<img src="'.DOMINIO.'img/top_mail.jpg" width="500" height="72" border="0"  />
				</td>
				</tr>
				<tr>
				<td style="font-size:12px; font-weight:bold; background-color:#f4f4f4">Subscriptions.</td>
				</tr>
				<tr>
				<td><strong>Name and Last Name:</strong> '.cls_string($_POST["name"]).'</td>
				</tr>
				<tr>
				<td><strong>Email and Phone:</strong> '.cls_string($_POST["email"]).'</td>
				</tr>
				<tr>
				<td style="background-color:#f4f4f4; text-align:center">Generated by: <a href="http://maoghost.com/">maoghost.com</a></td>
				</tr>
				</table></body>
				</html>';
		
		$list = array($empresa[email],$_POST[email]);
		for ($i=0;$i<count($list);$i++){				 
			$owner_email = $list[$i];//$_POST[email];
			$headers  = 'MIME-Version: 1.0' . "\r\n";
			$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
			$headers .= 'To: '.cls_string($_POST['name']).' <'.$owner_email.'>' . "\r\n";
			$headers .= 'From: '.$empresa['name'].' <'.$empresa['email'].'>' . "\r\n";
			$subject = 'A message from '.$empresa['name'].' Corporate Web ' . $_POST['name'];
			$messageBody = $body;
			//if($_POST["stripHTML"] == 'true'){
				//$messageBody = strip_tags($messageBody);
			//}
			try{
				if(!mail($owner_email, $subject, $messageBody, $headers)){
					
					mensajes("Error!", "We can not send your email, please try again!");
					break;
				}else{
					$paso = true;
				}
			}catch(Exception $e){
				echo $e->getMessage() ."\n";
				break;
			}
		}//for
		
		mensajes("Process Successfully.", "Subscription sent Successfully");
	}//if sumito
	 
?>

<div class="row panel">
	<h3 >Subscription</h3>
	<div class="large-12 columns  radius">	
		<form data-abide action="index.php?current=subscription" method="post" >
			<div class="name-field">
				<label>Your name <small>required</small></label>
				<input type="text" name="name" required pattern="[a-zA-Z]+" placeholder="Full Name">
				<small class="error">Name is required and must be a string.</small>
			</div>
			<div class="email-field">
				<label>Email <small>required</small></label>
				<input type="email" name="email" placeholder="your@email.com" required>
				<small class="error">An email address is required.</small>
			</div>
			<button type="submit">Submit</button>
		</form>
	</div>	
	
		
</div>	